USE [master]
GO

/****** Object:  Database [propertyX]    Script Date: 3/10/2022 2:49:55 PM ******/
CREATE DATABASE [propertyX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'propEx_records', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\propEx_records.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'propEx_records_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\propEx_records_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [propertyX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [propertyX] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [propertyX] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [propertyX] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [propertyX] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [propertyX] SET ARITHABORT OFF 
GO

ALTER DATABASE [propertyX] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [propertyX] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [propertyX] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [propertyX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [propertyX] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [propertyX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [propertyX] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [propertyX] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [propertyX] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [propertyX] SET  DISABLE_BROKER 
GO

ALTER DATABASE [propertyX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [propertyX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [propertyX] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [propertyX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [propertyX] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [propertyX] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [propertyX] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [propertyX] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [propertyX] SET  MULTI_USER 
GO

ALTER DATABASE [propertyX] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [propertyX] SET DB_CHAINING OFF 
GO

ALTER DATABASE [propertyX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [propertyX] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [propertyX] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [propertyX] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [propertyX] SET QUERY_STORE = OFF
GO

ALTER DATABASE [propertyX] SET  READ_WRITE 
GO


